name: profesor_autoescuela_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: 
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2 
  http: ^1.1.2
  provider: 
  sqflite:
  path: ^1.8.3
  fluttertoast: ^8.2.4
  mockito: ^5.4.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.6
  table_calendar: ^3.0.9
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  test: ^1.24.9

flutter:
  uses-material-design: true
